"""Initial migration

Revision ID: 48b1499d2002
Revises:
Create Date: 2024-06-29 16:50:40.296484

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48b1499d2002"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cars",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("brand", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("capacity", sa.Float(), nullable=False),
        sa.Column("power", sa.Float(), nullable=True),
        sa.Column("fuel", sa.String(), nullable=True),
        sa.Column("transmission", sa.String(), nullable=True),
        sa.Column("drive", sa.String(), nullable=True),
        sa.Column("mileage", sa.Integer(), nullable=True),
        sa.Column("broken", sa.Boolean(), nullable=True),
        sa.Column("nodocs", sa.Boolean(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("price_estimation", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("city_ru", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("photo_url", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cars")
    # ### end Alembic commands ###
